helmDefaults:
  tillerNamespace: kube-system

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com/

environments:
  home:
    secrets:
      - environments/home/google-dynamic-dns-update/secrets.yaml
      - environments/home/traefik/secrets.yaml

releases:
  # kube-system
  - name: traefik
    namespace: kube-system
    chart: stable/traefik
    values:
      - ./environments/home/traefik/values.yaml.gotmpl
  - name: google-dynamic-dns-update
    namespace: kube-system
    chart: ../charts/google-dynamic-dns-update
    values:
      - ./templates/google-dns-values.yaml.gotmpl
  - name: metallb
    namespace: kube-system
    chart: stable/metallb
    values:
      - ./environments/home/metallb/values.yaml
  # monitoring
  - name: prometheus
    namespace: monitoring
    chart: stable/prometheus
    values:
      - ./environments/home/prometheus/values.yaml
  - name: grafana
    namespace: monitoring
    chart: stable/grafana
    values:
      - ./environments/home/grafana/values.yaml.gotmpl
