version: "3"

tasks:
  all:
    desc: Sync all deployments
    cmds:
      - echo "Attempting to Sync ALL"
      - helmfile -e home sync
    silent: true

  sync:
    desc: Sync helm deployments
    cmds:
      - echo "Attempting to Sync {{.CLI_ARGS}}"
      - helmfile -e home --selector=name={{.CLI_ARGS}} sync --skip-deps
    silent: true

  diff:
    desc: Diff helm deployments
    cmds:
      - echo "Attempting to diff {{.CLI_ARGS}}"
      - helmfile -e home --selector=name={{.CLI_ARGS}} diff --skip-deps
    silent: true
