# Base helmfile

bases:
  - "bases/repositories.yaml"
  - "bases/helmDefaults.yaml"
  - "bases/environments.yaml"

# Templating
# Uses Go templates for templating and the functions in the Sprig library.
templates:
  default: &default
    chart: stable/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: kube-system
    missingFileHandler: Warn
    values:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
    secrets:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/secrets.yaml
  home-assistant: &home-assistant
    <<: *default
    createNamespace: true
    namespace: "home-assistant"
  monitoring: &monitoring
    <<: *default
    chart: prometheus-community/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: "monitoring"
  games: &games
    <<: *default
    createNamespace: true
    namespace: "games"
  cert-manager: &cert-manager
    <<: *default
    chart: jetstack/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: "cert-manager"

# The desired states of Helm releases.
#
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
releases:
  - name: raw
    <<: *default
    chart: grahamplata/{{`{{ .Release.Name }}`}}
    version: 0.2.3
  - name: cert-manager
    <<: *cert-manager
    version: v1.6.1
  - name: prometheus
    <<: *monitoring
    version: 13.2.1
  - name: grafana
    <<: *monitoring
    chart: grafana/{{`{{ .Release.Name }}`}}
    version: 6.2.1
  - name: openfaas
    <<: *default
    namespace: openfaas
    chart: openfaas/{{`{{ .Release.Name }}`}}
    version: 10.0.8
  - name: quake-kube
    <<: *games
    chart: grahamplata/{{`{{ .Release.Name }}`}}
    version: 0.1.6
  - name: minecraft
    <<: *games
    chart: itzg/{{`{{ .Release.Name }}`}}
    version: 3.8.0
  - name: home-assistant
    <<: *home-assistant
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    version: 12.0.1
