# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: openfaas
    url: https://openfaas.github.io/faas-netes
  - name: jetstack
    url: https://charts.jetstack.io
  - name: minecraft
    url: https://itzg.github.io/minecraft-server-charts
  - name: grahamplata
    url: https://grahamplata.github.io/charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

# helmDefaults
# Values to set for args along with dedicated keys that can be set by contributers
helmDefaults: {}

# The list of environments managed by helmfile.
#
# The default is `environments: {"default": {}}` which implies:
#
# - `{{ .Environment.Name }}` evaluates to "default"
# - `{{ .Values }}` being empty
environments:
  home: {}

# Templating
# Uses Go templates for templating and the functions in the Sprig library.
templates:
  default: &default
    chart: stable/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: kube-system
    missingFileHandler: Warn
    values:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
    secrets:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/secrets.yaml
  home-assistant: &home-assistant
    <<: *default
    createNamespace: true
    namespace: "home-assistant"
  monitoring: &monitoring
    <<: *default
    chart: prometheus-community/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: "monitoring"
  games: &games
    <<: *default
    createNamespace: true
    namespace: "games"
  cert-manager: &cert-manager
    <<: *default
    chart: jetstack/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: "cert-manager"

# The desired states of Helm releases.
#
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
releases:
  - name: cert-manager
    <<: *cert-manager
    version: v1.6.1
  - name: prometheus
    <<: *monitoring
    version: 13.2.1
  - name: grafana
    <<: *monitoring
    chart: grafana/{{`{{ .Release.Name }}`}}
    version: 6.2.1
  - name: openfaas
    <<: *default
    namespace: openfaas
    chart: openfaas/{{`{{ .Release.Name }}`}}
    version: 10.0.8
  - name: quake-kube
    <<: *games
    chart: grahamplata/{{`{{ .Release.Name }}`}}
    version: 0.1.6
  - name: minecraft
    <<: *games
    chart: itzg/{{`{{ .Release.Name }}`}}
    version: 3.8.0
  - name: home-assistant
    <<: *home-assistant
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    version: 12.0.1
  # Orphaned resources
  - name: raw
    <<: *default
    chart: "./charts/{{`{{ .Release.Name }}`}}"
