# Base helmfile
bases:
  - "bases/repositories.yaml"
  - "bases/helmDefaults.yaml"
  - "bases/environments.yaml"

# Templating
# Uses Go templates for templating and the functions in the Sprig library.
templates:
  default: &default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - release/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml
      - release/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
    secrets:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/secrets.yaml

  # Local Chart inherits the default values but overrides the chart path
  local: &local
    chart: charts/{{`{{ .Release.Name }}`}}
    <<: *default

# The desired states of Helm releases.
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
releases:
  # Simple App
  - name: app
    namespace: default
    <<: *local

  # Applications
  - name: home-assistant
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    namespace: "home-assistant"
    version: 13.4.2
    <<: *default

  - name: photoprism
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    namespace: "photoprism"
    version: 7.1.2
    <<: *default

  # Ops
  - name: cert-manager
    chart: jetstack/{{`{{ .Release.Name }}`}}
    namespace: "cert-manager"
    version: v1.14.5
    <<: *default

  - name: traefik
    chart: traefik/{{`{{ .Release.Name }}`}}
    namespace: "traefik"
    version: 28.1.0
    <<: *default

  - name: kube-prometheus-stack
    chart: prometheus-community/{{`{{ .Release.Name }}`}}
    namespace: "monitoring"
    version: 43.2.1
    <<: *default

  - name: uptime-kuma
    chart: uptime-kuma/{{`{{ .Release.Name }}`}}
    namespace: "monitoring"
    version: 2.18.0
    <<: *default

    # Storage
  - name: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner/{{`{{ .Release.Name }}`}}
    namespace: "nfs-server"
    version: 4.0.17
    <<: *default
