# Base helmfile
#
bases:
  - "bases/repositories.yaml"
  - "bases/helmDefaults.yaml"
  - "bases/environments.yaml"

# Templating
# Uses Go templates for templating and the functions in the Sprig library.
#
templates:
  default: &default
    chart: stable/{{`{{ .Release.Name }}`}}
    createNamespace: true
    namespace: kube-system
    missingFileHandler: Warn
    values:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
    secrets:
      - helm/environment/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}/secrets.yaml
  home-assistant: &home-assistant
    <<: *default
    namespace: "home-assistant"
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
  photoprism: &photoprism
    <<: *home-assistant
    namespace: "photoprism"
  grahamplata: &grahamplata
    <<: *default
    chart: grahamplata/{{`{{ .Release.Name }}`}}
  cert-manager: &cert-manager
    <<: *default
    chart: jetstack/{{`{{ .Release.Name }}`}}
    namespace: "cert-manager"
  prometheus: &prometheus
    <<: *default
    chart: prometheus-community/{{`{{ .Release.Name }}`}}
    namespace: "monitoring"
  ingress-nginx: &ingress-nginx
    <<: *default
    chart: ingress-nginx/{{`{{ .Release.Name }}`}}
    namespace: "ingress-nginx"
  nfs-subdir-external-provisioner: &nfs-subdir-external-provisioner
    <<: *default
    chart: nfs-subdir-external-provisioner/{{`{{ .Release.Name }}`}}
    namespace: "ingress-nginx"
  linkerd: &linkerd
    <<: *default
    chart: linkerd/linkerd2
    # The chart creates linkerd namespace
    createNamespace: false
    condition: linkerd.enabled
  linkerd-viz: &linkerd-viz
    <<: *default
    chart: linkerd/linkerd-viz
    createNamespace: true

# The desired states of Helm releases.
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
#
releases:
  # Misc
  - name: raw
    <<: *grahamplata
    version: 0.2.3

  # Games
  - name: quake-kube
    <<: *grahamplata
    chart: grahamplata/{{`{{ .Release.Name }}`}}
    version: 0.1.6
    namespace: "games"

  # Applications
  - name: home-assistant
    <<: *home-assistant
    version: 13.4.2
  - name: photoprism
    <<: *photoprism
    version: 7.1.2

  # Ops
  - name: cert-manager
    <<: *cert-manager
    version: v1.10.1
  - name: ingress-nginx
    <<: *ingress-nginx
    version: 4.2.2
  - name: nfs-subdir-external-provisioner
    <<: *nfs-subdir-external-provisioner
    namespace: "nfs-server"
    version: 4.0.17
  - name: kube-prometheus-stack
    <<: *prometheus
    version: 43.2.1

  # # Mesh
  # - name: linkerd
  #   <<: *linkerd
  #   version: 2.11.4
  # - name: linkerd-viz
  #   <<: *linkerd-viz
