version: "3"

# Global environment variables
env:
  DEFAULT: "Take out the trash!"

# Global include .env
dotenv: [".env"]

# Global Variables
vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel

includes:
  setup: .taskfiles/Taskfile_{{OS}}.yml
  helmfile: .taskfiles/Taskfile_helmfile.yml
  k3s: .taskfiles/Taskfile_k3s.yml

tasks:
  default:
    cmds:
      - task -l
    silent: true
