# Default values for cert-manager.

global:
  imagePullSecrets: []
  priorityClassName: ""
  rbac:
    create: true
  podSecurityPolicy:
    enabled: false
    useAppArmor: true
  logLevel: 2
  leaderElection:
    namespace: "cert-manager"
installCRDs: true
replicaCount: 1
image:
  repository: quay.io/jetstack/cert-manager-controller
  pullPolicy: IfNotPresent
clusterResourceNamespace: ""
serviceAccount:
  create: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
webhook:
  replicaCount: 1
  timeoutSeconds: 10
  strategy: {}
  securityContext: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podLabels: {}
  image:
    repository: quay.io/jetstack/cert-manager-webhook
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
  securePort: 10250
  hostNetwork: false
cainjector:
  enabled: true
  replicaCount: 1
  strategy: {}
  securityContext: {}
  containerSecurityContext: {}
  extraArgs: []
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podLabels: {}
  image:
    repository: quay.io/jetstack/cert-manager-cainjector
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
