apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: prometheus-server
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube"
