apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  storageClassName: prometheus-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi