apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: graham.plata@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-cloudflare
    solvers:
      - dns01:
          cloudflare:
            email: graham.plata@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
