ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "traefik"
    tls:
      - hosts:
          - photo.mooncity.dev
        secretName: photo-tls
    hosts:
      - host: photo.mooncity.dev
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: photoprism
                port:
                  number: 2342

persistence:
  config:
    enabled: true
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /photoprism/storage

  originals:
    enabled: true
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 20Gi
    mountPath: "/photoprism/originals"
