rbac:
  create: true

serviceAccounts:
  alertmanager:
    create: false
  pushgateway:
    create: false

alertmanager:
  enabled: false

configmapReload:
  prometheus:
    enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: true
  hostNetwork: true
  name: node-exporter
  image:
    repository: quay.io/prometheus/node-exporter
    tag: v1.0.1
    pullPolicy: IfNotPresent

server:
  enabled: true
  name: server
  persistentVolume:
    enabled: false
  emptyDir:
    sizeLimit: ""

pushgateway:
  enabled: false
