rbac:
  create: true

podSecurityPolicy:
  enabled: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

server:
  enabled: true

  persistentVolume:
    enabled: true
    mountPath: /data
    size: 1Gi

pushgateway:
  enabled: false
