grafana:
    adminPassword: ENC[AES256_GCM,data:Mgyxxa57gGXs1ujBvg==,iv:4Snsm5bTPeCUMV7TqhB0LvQI874+o8MPBUkNtBSSLO0=,tag:thKdExxBmlwqX+k8sx5zyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-10T01:03:31Z"
    mac: ENC[AES256_GCM,data:IF8XWaDVqP+n/38AMc5tx+Y6h8lH0CaFAsyyhBW6nRz6J0+lZo6V7tTiwvDux1o5sZya+2iYK1SwscnXmv32m3TM24mLW7uxJTLBllg9E13+ijnA1XYjtG3lFLCAO+tiI2CI/1jjf6z9/iWpshYehYoXa92DKJP72cjWBv0tb0k=,iv:ZZnoT9K8SmlY8PBb6FysGTvb3MOygTy1DCAXu17eYis=,tag:6C0DX/88/nPBVaLgSLyMHQ==,type:str]
    pgp:
        - created_at: "2023-01-10T01:02:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/NKTSBqvTB6ARAAH23FCGDrdcbAU1xxYYAcWovemACnrIN21nBQ3/2ZEzbM
            rDmxe1bYVsv4Q1L2LwdpcG0I8vu5TAQiKwbAxaUjYHqPQr2VABVq/sClDWbOnDLJ
            UJBzwpxZtGjnf2aP4x22bR4DuM1JFGvGx9jWD7YvlMPm0HbArSrUUUBkeaC67dUU
            8tmTqk44OlGd213Fh2a3WY9lCrbZo3dP537RaJGm65T/Y80BVJvtFx+g3A1gvuRZ
            CKpQGHXvlmIEyEb/9iWRYaFQxLHTlUc2Mglhy3war8WReaKCdXeuqdEDmHWT2uLl
            9LBTsqcf9xNxlcCh0n0wnGRCNjCMskT1n8y3oIdl35QRuHCt/zq56FUgkpH+MwbT
            f+iYwl8s23VqM+Xc15uCxmvpkRV7ddIo+zKYMp+n5+fk4no0ce9tvOiFnZAJ4fUW
            VEwEruQMVDGLF0cODBm3pg/Fb0bFw3qT3bOYhQSLLWtW/QmLb3b8WaHr3x8YiZ9P
            wnwxOuw/VON82s8mmC3pIgH92oM04DnWYNcH3myzcpjidLd8TUMM91w5uZQZqSF7
            5XgZmPyltMA1BwfmDDO14yayfEoinECuMbrDnEz6buFX7s4y+rjrQyA4e/gQtzN/
            0xZdsqvk1YI6YxguSi6yFZ51FdsRRBEMCUJx0ugKVIi5xS8DLTjtKumbpWuycVTS
            5gFU8L1m7DkkZwMKZWninGo9qcrf/mQ2i6ANMRYLezszeLd6TqN4Y8NBKBOsfA5N
            blc1zq9fCkBNrCinUHsLurHkuh3lv9mMueUSUTSHeuVj6eLhkzJyAA==
            =//Ra
            -----END PGP MESSAGE-----
          fp: BC8DF74B855D6575ED4878E8962D032461639065
    unencrypted_suffix: _unencrypted
    version: 3.7.1
