apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: prometheus-volume
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
