apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-volume
  namespace: kube-system
  labels:
    type: local
spec:
  storageClassName: traefik-volume
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube"
