minecraftServer:
    rcon:
        enabled: ENC[AES256_GCM,data:zf56OcA=,iv:hlV/5NMA5KWQE4HFbrtsKXXbZErJeLi03ADp8CGww9c=,tag:WJideZguEWJgrrJq7Bn0Tw==,type:bool]
        password: ENC[AES256_GCM,data:BD2OEisf7ZdZC2kXXkE=,iv:l7DmyTUay778TGFmNxLXXNgxFIti3lO8wcdw1N54bhU=,tag:zOiIeptWiVxIF4LTFj9UHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-22T00:11:55Z'
    mac: ENC[AES256_GCM,data:JqvcpoLyWX5m8cHbV8gshZTzgEEp4hAv/ysoNOtiviUNq5qX66apQJxdbaqef/XOUb9JDAOB+FaAhNgUt2GWJ1Hcm13HCpkapbDLJAqz8YaAVcu1aiL5b+GtBZqPYvmtY1791T+UO1u1bNJxWHu4XUqvbTgKImLciTTGLRz2ylo=,iv:ELiOKg0SzBUDSvl5CXKzB7HQQuELV5/rAkoNFYxFFxg=,tag:DEK4C+1920wfDCsGGoF2rw==,type:str]
    pgp:
    -   created_at: '2021-02-22T00:11:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/NKTSBqvTB6ARAAnlcX7JwmOt32gzz3XBKdMeyRqH2UfcxJD6pWVhtqKrKP
            Z2VmLpdJxjgNQTRID+xgU+z2UK0jT5dKxN/eN8U7SS4aHzOuT5kepSZ2BPanSADx
            fly+2rw//saFHnQl3QPJgicaUhjnHMxbq7C9qwnEveyNnAUHf0ObPAlrljKeQyLg
            4am42eV5hRo1Uz7qOtwgA+As/VxzSduVlwMXUkrEZJa7iVcEX+u832us+Wq/T0Oq
            8qBDixDmuqEakGOWZhWwJqs8JE5RbS1AZ6pqsqBWAZCyfmm+r+EexXs/ViS9VUBd
            HXDzTtc0rAoSAi3Zm513oJm2HACPEBWu5KPrm2/oEiIO51MP7lkSIyAqvbLUZqi9
            gFsD7UZ17BR22I6M/63S3eWNfvmeosN2c3BAtrXlAEOsG0UeDVgZZVRh7Ld37vcG
            +AWO0CTyWZcPUK8hSepKOYrgl00BVeESJkTfV9PKiFdQqYKueN2/uoDiVW3qHvxU
            yLlul5X5zSLDbgqHMdRGEkC8iFF8Qyyql9Ug6i4aeYIDpg9ISjz10E/LAUiTm64a
            RJkNNbyuTn0ncSwgl1AGsQrJ6Md2JzrNarXFciXfE6bUEpNpUc0sbi9yQNstCvXn
            gQlhlEA75nOIBVMqD+axSUkl2o++g44PhGA2XYiOz03A9cA8VMmFQ64Wlige/GrS
            XgEvCbJyG+oUG92YdMWYK4Wtbxo12wqM/RKDGUIeJYwXXGETj70J8m9y5faqO5xB
            NT4WmaLTbpYDbf+F15u77UIJDZNqdgQdeBSwU8GUuF227q47URq33ApYFfRFt9I=
            =KOff
            -----END PGP MESSAGE-----
        fp: BC8DF74B855D6575ED4878E8962D032461639065
    unencrypted_suffix: _unencrypted
    version: 3.6.1
