nfs:
    server: ENC[AES256_GCM,data:z268blfy1FXYNaek,iv:SGY37m0SiqYg2FxkrMt2KZcYUpl1j407txjOKsa2Q1A=,tag:aLDjl1OnvHCtZRaHSLgapw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-09T19:51:40Z'
    mac: ENC[AES256_GCM,data:0ZT7FBh3QfVP5xEA9qgEn2uerFw/b4E7dG3D8FrIo3azQDHNaWst/eyb1UnYXRL5v3RjOXKAT6jOcNtrNEZLXzY/mJC2US173n2wnYRJ9bQLDMLzFiKdBQgf9VQp+lqrsrGE0jJIGV4Q2JvY9NTSWmN/XC5yfO8W+sMD7dWiuPc=,iv:+UT5uZfdtmqdUIA8CNqAvxJjAaLvbclSM0H7EZVk0J8=,tag:UIicF57uNYuo9JRnH8sgZQ==,type:str]
    pgp:
    -   created_at: '2020-08-09T19:51:40Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/NKTSBqvTB6ARAACc0j3gqP7Hr9prBdZ5n1bohpeBifd2335tVP3lbkJwJe
            ToLJQ/6o1Y4J6ag8SIt7thHGTLdRJGk+BxkBh5Oy577aau/M2JO1UBAmvlpuQzHO
            9rW2eEN6d7wyv+wcgbaaJ626maQVtdcvt/VN+gr6Dd+Zhh7xip3M+qRBD9PYK+lK
            YKaYoyfhtXd7piI/LoXEOq/7NxNy+Ij2v/fD4T6sQa4xFRPxzY5Pueus0LGupp8O
            aDiUPGmkgIFykzG+I2wNjUTRHFCZ+Wiod6QqYoGQC3OTTn9JeA+HCrxjCFkEvZgb
            6QDdbHkqkYV6/IYLwGJu4fM4ATOq3ea75caKugk8afZPYD8XU2hfs+0p3MYBr9/z
            DyiSRB3i9YwcDwTmEs4I6NtNdDbWRxI6yJl44VtJ/J9EoFzYgtOO71kzPgTBQQIs
            OwRYRFnI92xdfYZXqSDd5KVUR+aop/EteYsUy2zvLPbyOXIv4RdbTjb4/mKMYXoY
            +Kxel6WxgDTJNyY8m4VC9Du5ekaRKiwlCK0zAyN0G96bMF7mG9lyTMe53Hg3zLr+
            s0F61bCbUaTYMUD1zx1vp/sRSBUPDk2JXtTlupeOBs/ofkFhbJyi4o8DmGr9TpHc
            P5cMOkxIkoPNYbRvp2+Y5VgugkEnHuk9gLWePoddLw/07I8I55/mroamyX6jlM3S
            4AHkzW2AKotBJh2EdBLdxU63XuHTsuA24KDhSdHgReILuueW4IbloPliHSm8CHtJ
            n1odwrFeJjBzpLvPMhc77OLHOz4aI5rgKuTjdfdL0nl8aZV23/zspQkN4komO2Xh
            RY8A
            =RmyR
            -----END PGP MESSAGE-----
        fp: BC8DF74B855D6575ED4878E8962D032461639065
    unencrypted_suffix: _unencrypted
    version: 3.5.0
