# Default values for metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# To configure MetalLB, you must specify ONE of the following two
# options.

# existingConfigMap specifies the name of an externally-defined
# ConfigMap to use as the configuration. Helm will not manage the
# contents of this ConfigMap, it is your responsibility to create it.
configInline:
  # Example ARP Configuration
  address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.1.240-192.168.1.250
