prometheus:
  enabled: false

quakeServer:
  eula: true

  fragLimit: 25
  timeLimit: 15m
  bot:
    minPlayers: 3
  game:
    motd: "Welcome to MoonCity Quake Server"
    type: FreeForAll
    forceRespawn: false
    inactivity: 10m
    quadFactor: 3
    weaponRespawn: 3
  server:
    hostname: "mooncity-quake3"
    maxClients: 12
  maps:
  - name: q3dm7
    type: FreeForAll
    timeLimit: 10m
  - name: q3wctf1
    type: CaptureTheFlag
    captureLimit: 8
  - name: q3dm17
    type: FreeForAll
  - name: q3tourney2
    type: Tournament
  - name: q3wctf3
    type: CaptureTheFlag
    captureLimit: 8
  - name: ztn3tourney1
    type: Tournament

service:
  type: ClusterIP
  clientPort: 8080
  serverPort: 27960
  contentPort: 9090

persistence:
  annotations: {}
  dataDir:
    enabled: true
    Size: 1Gi
