apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: home-assistant
  name: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status: {}
