apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: home-assistant
  name: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data
    type: ""
  volumeMode: Filesystem
