apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: prometheus-server
  name: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-server
    namespace: monitoring
  hostPath:
    path: /data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status: {}
