apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server
  namespace: monitoring
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
