apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
    namespace: monitoring
  hostPath:
    path: /data
    type: ""
  volumeMode: Filesystem
