basic_auth: true
generateBasicAuth: true

clusterRole: false
createCRDs: true
openfaasPRO: false

nodeSelector:
  beta.kubernetes.io/arch: arm64

gateway:
  directFunctions: true

oidcAuthPlugin:
  enabled: false

operator:
  create: false

prometheus:
  image: prom/prometheus:v2.11.0
  resources:
    requests:
      memory: "100Mi"
alertmanager:
  create: false

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.20.1-armhf
  replicas: 1

ingressOperator:
  create: false

nats:
  enableMonitoring: false
  metrics:
    # Should stay off by default because the exporter is not multi-arch (yet)
    enabled: false
