prometheus:
  serviceMonitor:
    enabled: true

persistence:
  config:
    enabled: true
  usb:
    enabled: false
    type: hostPath
    hostPath: /path/to/device

# -- Enable devices to be discoverable
hostNetwork: true

http:
  server_host: 0.0.0.0
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
  # Pod CIDR
  - 10.69.0.0/16
  - 10.42.3.0/24
  - 10.42.2.0/24
  - 10.42.1.0/24
  - 10.42.0.0/24
  # Node CIDR
  - 192.168.6.0/24
  # tailscale
  - 100.64.0.0/10
