image:
  repository: homeassistant/home-assistant
  tag: 2022.7.4

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server-1
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: app
              operator: In
              values:
                - zigbee-controller

ingress:
  main:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "nginx"
    tls:
      - hosts:
          - home.mooncity.dev
        secretName: home-tls
    hosts:
      - host: home.mooncity.dev
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123

service:
  main:
    ports:
      http:
        port: 8123

prometheus:
  serviceMonitor:
    enabled: false

persistence:
  config:
    enabled: true
    storageClass: "nfs-client"
  usb0:
    enabled: true
    type: hostPath
    hostPath: /dev/ttyUSB0
  usb1:
    enabled: true
    type: hostPath
    hostPath: /dev/ttyUSB1

securityContext:
  privileged: true

addons:
  codeserver:
    enabled: true
    args:
      - --auth
      - none
      - --user-data-dir
      - /data/config/.vscode
    volumeMounts:
      - name: config
        mountPath: /data/config
