image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: 2021.4.4

strategy:
  type: Recreate

service:
  port:
    port: 8123

prometheus:
  serviceMonitor:
    enabled: true

persistence:
  config:
    enabled: true
    emptyDir:
      enabled: false
