digitalocean:
    apiToken: ENC[AES256_GCM,data:8Fpg9PWXB5I4bJEdJ+j/stf9ygddQjY1V+xS8SZIdCpTZJAeIQ3h83Y8W2zYP4sbuokFh0mHoqaMcl4wH+8dTQ==,iv:cCAjkBOpSYY5ulEpcEsa30o92lFkzJubJa+vU+oSCHY=,tag:0Nkkhp2w3gyC9qphBo9d3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-10-26T00:50:35Z'
    mac: ENC[AES256_GCM,data:+5wMT0x/vBt20eRfU7ta86+6jD1jwgiGFEsg7teaJwVazHxycujbvZF6IiNes4mwr9gV36KokF/AunwvAhAml91Ci5CToWSAm9Qv47MEugBsFFEZqO8sdILeRXG3n0Nlk8WyDZiX3lygMllr3PiYJ3F/QhqPl7DsGdFWRSN9Wc0=,iv:rpoRkZwHpvnKhXgpnaugBlMtXWDwg5tWeXIosGLB+lY=,tag:wZRfv18h7gUadQn+Z+b4UQ==,type:str]
    pgp:
    -   created_at: '2019-10-26T00:50:34Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/NKTSBqvTB6ARAAFblApuWQhq9zSpgs/OHY06otAHMN7Rb3X1RXu6VvVSiS
            FzJxWkqig2thFzSga51evhgvvcLmrrgbNRYLRdRV2UIyClVQOhxpDGgq9fTKgy4+
            6FxMtMh1B4I/h1s0L7iRrkfJbcX1Sr9b1U9H4G5RIbTb2vRvEGAiMAlHZqMUumi7
            p3hTZ3WHTLO2pdQ47d5gniocZRGzfiappKz6KTM7YMG1Jlzh5bwAlqfaNJBoRU4x
            3FwPLSYEXbv53ir7rWCja9nHXXIr3O36awPx+j1nRcfRFy3aPEbAQuZVhv/Pd/r/
            4gPgvbCEboXxJQ44hAvZ88EjGuMyaPHznUp0khR+40dBFwQpdczPkRT0UQj8NJ8h
            enup3SulbjsKHzV4Y1vdcrYvKDsQXiF78YHwxqFJ1TAsDs/d5BqHhkm8OtSAP89g
            WSIW4J80pug90hShAZSfDlKwXCkqcnDmZP1hbVRNr+x7zr25W3p5qVv9/qEdVcUC
            HxEm88DJ4+/EZSm7VfFVFrMiax1fOxR4y6TZLSZSKyrdxzKQ69n/fSKJI5Pgs/Gh
            +UuEA1G+/V6M+E5rgwYyrg5lkHlWLd5rwEN1pHMYklcL98p7Z5A4hrDoGcfBoyz7
            br74QGBxSyWtI5K8C7XWQjkAhTYmzwkkZ/dZ1njv2bNnK6OSNuvfdQCdXXyndsPS
            4AHkMy7+is+OG6DDGIB0h1GigOGDROCk4LLhNDTgUOKJLuiv4LrlW8BDKOxgTEF3
            KmRqatXjBvlf+foGlhvr/eBcmOJpjaTgSOT4yGA5whnxNC3UTgRcZAdx4i1gT5bh
            4TUA
            =5hzP
            -----END PGP MESSAGE-----
        fp: BC8DF74B855D6575ED4878E8962D032461639065
    unencrypted_suffix: _unencrypted
    version: 3.4.0
