dns:
-   auth: ENC[AES256_GCM,data:b0iYsUIiGwM0/dSxJnzX6TQrYlU9hwXKY6rUaJ0jLWdV,iv:HsrzLpX4slZkfNu+laIDxXXURcpw6/cgU2sGvNCoblQ=,tag:6m+ejrb5sKePMpv589iPOQ==,type:str]
    host: ENC[AES256_GCM,data:TyPD7shS99d6yMSvWWp6fHs+Xbg=,iv:aUmxlBh72GBdiMe/5zUTJGeGYE/zunvwt4SVyNmRz6M=,tag:VW5ki7GyVeP6hCSJwXSpww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-08-02T23:53:35Z'
    mac: ENC[AES256_GCM,data:h+IKAOMkBQRUEVOR6xK6jicq/HD99f++3eIyhq7U8jXn4/RtGvbyxvPTtwoOq5ziey/i0g0tQbMxACAyqsh0e42kdxVmEwM+1AY+PVCOTGQO/B9zRPW5Pjheo6KLTyx5/abn8jEBxSdEgHLzYxqpUzrJh/KmSrGQD1zF5g6cJfk=,iv:yQMh+wv6vfqy4KKzpLZuXAXaeZnv0BnE4LQldFm1kh4=,tag:b3+p6ClkR5vAU9XUAAriVw==,type:str]
    pgp:
    -   created_at: '2019-08-02T23:53:35Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/NKTSBqvTB6ARAAOewL2kDFIGmjzSiLqR5goWuqn1RH/SRObKawFPMe+4j3
            Q2l1Y4dblkGASwVEJe/hk8cqunaAHAaF7oLMjnAuP2S7zhkPwj0APul0s1tnCP8C
            U8ITvqCEiRrPg/u3LwNR5Gs3usUcgjipxQ8HVerLmXfT56ueeuhRdBT76xdvWM8j
            F9zLsuvqV/9szUBJdTr3pXD/5JspITifpOTHN+VcfGqO8DL6WHmH6QxTdJn2WPan
            qjLGYv6gZrAynik5RIfPb7dqXFfCoiIrgJPYVgQsSTWXlr/ByeHbLycnk4trBn8O
            84jaqXLjpTWa1ayGtVXKqPI/AyVfVWICNe70vIrm7efS0PTVfh2t47VRqhYcXdYf
            xS4CxLoyUJAvqWhqY9dj/mm+JWqp9zXCUm6ugiKs4qNW5Pcl/GTm27dTewD4LbuV
            v395FH66IQPMtlBHHtGcc4HWbKA7y09IB+uurIBR4Z06+U/fb1MQh3UVPTZLJ0da
            HOLLGy9sRV6/WHO6DOhgkdJbJc79PY4+wvaK1xPOYKFqx9N+EAaxkvKtLYhGybXq
            R9i8p5PfIaVES4WUNFNcJYeUyi4cZnqf+JQXfwvU8NXTl3LY50W1k6jkUuWbBYwS
            f5b562iEQ0rZMALQ8bjHiZYShr8nGhdimSDGzlWUkTJbqAdNPGh8KLh1GsKsixfS
            4AHkN8xS1nM0bETymNaV7LB23OG0r+B64AvhNIDgTuJBNwmC4GjlM426XSfRGvLr
            OhTqrKWtkkYY1hKl/WRHTK4utnJMpVHg2+QhH0tSGsfGmcDM3W2pA0M74geA6wDh
            r8IA
            =nDpQ
            -----END PGP MESSAGE-----
        fp: BC8DF74B855D6575ED4878E8962D032461639065
    unencrypted_suffix: _unencrypted
    version: 3.3.0
