installCRDs: true

replicaCount: 1

ingressShim:
  {}
  # defaultIssuerName: ""
  # defaultIssuerKind: ""
  # defaultIssuerGroup: ""

prometheus:
  enabled: true

webhook:
  replicaCount: 1
  timeoutSeconds: 10

cainjector:
  enabled: true
  replicaCount: 1

startupapicheck:
  enabled: true
