nameOverride: external-dns
image:
  registry: docker.io
  repository: vchrisb/external-dns
  tag: v0.5.18
  pullPolicy: IfNotPresent
sources:
  - service
  - ingress
provider: google
google:
  serviceAccountSecret: external-dns
  serviceAccountSecretKey: "credentials.json"
registry: "txt"
txtOwnerId: "external-dns"
resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m
rbac:
  create: true
  apiVersion: v1
